### ISSUE TITLE
hardware: Possible incorrect component in Logic BOM

### ISSUE THREAD

**Issue by jawsper** [friedpies/kelpie-pocket-synth#43]
I saw in the BOM of the Logic board that you're referring to the AP7317-33SR voltage regulator for the SGTL5000 audio chip. I think this may be an error, since the audio chip needs a 1.1V - 2.0V level on that pin and this is a 3.3V regulator. The official Audio Shield uses the AP7317-18SR (package code SD) which does supply the correct level.

I hope this is only an error in the BOM, because it may very well break the audio chip.

**Comment by friedpies** [comment]
hey @jawsper, I believe you are correct! Thank you for catching this error. I'll update the Eagle files and BOM. I really appreciate it. Also will swap those parts out on my boards. Luckily haven't broken anything yet!!
